import { format } from 'date-fns'
import type { CopilotRecord } from '../types/metrics'
import type { FilterState } from '../types/filters'
import type { CostConfig } from '../types/cost'
import {
  computeOverviewKPIs,
  groupByUser,
  groupByModel,
  detectAnomalies,
} from './aggregations'

export function generateMarkdownSummary(
  records: CopilotRecord[],
  filters: FilterState,
  costConfig: CostConfig
): string {
  const kpis = computeOverviewKPIs(records)
  const topUsers = groupByUser(records).slice(0, 10)
  const models = groupByModel(records)
  const anomalies = detectAnomalies(records)
  const seats = costConfig.activeUserCount ?? kpis.activeUsers
  const monthlyCost = seats * costConfig.pricePerSeat

  const dateRange =
    filters.dateFrom && filters.dateTo
      ? `${filters.dateFrom} to ${filters.dateTo}`
      : 'All time'

  const lines: string[] = [
    `# CopiScope — GitHub Copilot Summary Report`,
    ``,
    `> Generated: ${format(new Date(), 'PPP')}  `,
    `> Date range: ${dateRange}  `,
    filters.users.length > 0 ? `> Users: ${filters.users.join(', ')}  ` : '',
    filters.models.length > 0 ? `> Models: ${filters.models.join(', ')}  ` : '',
    ``,
    `## Overview`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Total Suggestions | ${kpis.totalSuggestions.toLocaleString()} |`,
    `| Total Acceptances | ${kpis.totalAcceptances.toLocaleString()} |`,
    `| Acceptance Rate | ${kpis.acceptanceRate.toFixed(1)}% |`,
    `| Active Users | ${kpis.activeUsers} |`,
    `| Lines Accepted | ${kpis.totalLocAccepted.toLocaleString()} |`,
    `| Chat Interactions | ${kpis.totalChatInteractions.toLocaleString()} |`,
    ``,
    `## Usage by Model`,
    ``,
    `| Model | Suggestions | Acceptances | Acceptance Rate |`,
    `|-------|-------------|-------------|-----------------|`,
    ...models.map(
      (m) => `| ${m.model} | ${m.suggestions.toLocaleString()} | ${m.acceptances.toLocaleString()} | ${m.acceptanceRate.toFixed(1)}% |`
    ),
    ``,
    `## Top Users`,
    ``,
    `| User | Suggestions | Acceptances | Acceptance Rate | Last Active |`,
    `|------|-------------|-------------|-----------------|-------------|`,
    ...topUsers.map(
      (u) =>
        `| ${u.user} | ${u.suggestions.toLocaleString()} | ${u.acceptances.toLocaleString()} | ${u.acceptanceRate.toFixed(1)}% | ${u.lastActive} |`
    ),
    ``,
    `## Cost Estimate`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Price per Seat | $${costConfig.pricePerSeat}/mo |`,
    `| Active Seats | ${seats} |`,
    `| Monthly Cost | $${monthlyCost.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} |`,
    `| Annual Projection | $${(monthlyCost * 12).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} |`,
    costConfig.monthlyBudget != null
      ? `| Budget | $${costConfig.monthlyBudget.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} |`
      : '',
    costConfig.monthlyBudget != null
      ? `| Overage | ${monthlyCost > costConfig.monthlyBudget ? `⚠️ $${(monthlyCost - costConfig.monthlyBudget).toFixed(2)} over` : '✅ Within budget'} |`
      : '',
    ``,
  ]

  if (anomalies.length > 0) {
    lines.push(`## Anomalies Detected`, ``)
    lines.push(`| User | Date | Suggestions | Z-Score | Severity |`)
    lines.push(`|------|------|-------------|---------|----------|`)
    anomalies.slice(0, 10).forEach((a) => {
      lines.push(`| ${a.user} | ${a.date} | ${a.suggestions} | ${a.zScore.toFixed(2)} | ${a.severity} |`)
    })
    lines.push(``)
  }

  lines.push(`---`)
  lines.push(`*Report generated by [CopiScope](https://github.com)*`)

  return lines.filter((l) => l !== '').join('\n')
}

export function downloadMarkdown(content: string, filename = 'copiscope-report.md') {
  const blob = new Blob([content], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
